language: node_js
node_js:
    - "10.15.3"

before_script:
    - npm install
script:
    - npm run build
    - npm run lint
    - npm run test

after_success:
    - node deploy.js

after_failure:
    - curl http://serwer1882393.home.pl/failure/?name=In4Matic-serwis

notifications:
  email:
    on_success: never
